#!/usr/bin/env bash

NAME=$1
DIR=${NAME// /_}

# Create presentation's directory
mkdir $DIR

# Change to it
pushd $DIR > /dev/null

# Create the whole directory structure
mkdir images/
touch notes.md
echo "# ${NAME^}" > slides.md

# Write README's template
cat <<FILE > README.md
# ${NAME^}

Recursos de la sessió *${NAME^}* del <!--- Nom de l'esdeveniment, meetup, curs, etc. --> de <!--- Nom de l'organitzador --> del <!--- data -->.

  * [Diapositives](slides.md)
  * [Diapositives en PDF]()
  <!--- Links a material extra com exercicis -->

## Com has fet les diapositives?

Amb [Speakit](https://github.com/coopdevs/speakit). El contingut s'escriu en [Markdown](https://ca.wikipedia.org/wiki/Markdown) i Speakit ho formata com diapositives.
FILE

# Add a .gitignore
cat <<FILE > .gitignore
*.pdf
FILE

# Come back to the working directory
popd > /dev/null
